# Generated by Django 5.0.14 on 2025-05-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='justificacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
