# Generated by Django 4.2.11 on 2025-05-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0003_estudiante_activo'),
        ('usuarios', '0002_personaladministrativo_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='padre',
            name='estudiantes',
            field=models.ManyToManyField(related_name='padres', to='estudiantes.estudiante'),
        ),
    ]
